### ISSUE TITLE
http://www.nanayun.cn/morningBird.html#/ 打不开

### ISSUE THREAD

**Issue by xujinjiao** [IceSeaOnly/morningBirder#1]
http://www.nanayun.cn/morningBird.html#/

**Comment by xujinjiao** [comment]
这个项目怎么运行|??

**Comment by IceSeaOnly** [comment]
你好，链接已经修复，欢迎查看。
前端直接放在浏览器中即可打开，合约需要部署在星云链上，你可以查看星云链官方文档了解更多。
